kind: Service
apiVersion: v1
metadata:
  name:  {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    tags.datadoghq.com/version: {{ .Values.deployment.version }}
    tags.datadoghq.com/service: "tms"
    tags.datadoghq.com/env: {{ .Values.deployment.environment }}
spec:
  type: ClusterIP
  selector:
    app:  {{ .Values.deployment.name }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
