name: Workflow A
on:
  workflow_dispatch:

jobs:
  WA:
    name: Calling Workflow B
    uses: ./.github/workflows/B.yaml
  WB:
    needs: [WA]
    name: Calling Workflow C - ${{ needs.WA.BTask.outputs.env }}
    uses: ./.github/workflows/C.yaml
