name: Workflow A
on:
  workflow_dispatch:

jobs:
  name: Workflow A
  runs-on: ubuntu-latest
  WA:
    name: Calling Workflow B
    uses: ./.github/workflows/B.yaml
  WB:
    name: Calling Workflow C
    uses: ./.github/workflows/C.yaml
