name: Workflow B
on:
  workflow_call:

jobs:
  BTask:
    name: Workflow B
    runs-on: ubuntu-latest
    steps:
      - name: Using Checkout @v4
        uses: actions/checkout@v4
      - name: Running Workflow B
        run: |
          echo "Hello Im workflow B!"
