name: Workflow B
on:
  workflow_call:
    outputs:
      description: 'Hi TMS'
      value: ${{BTask.env.value}}

jobs:
  BTask:
    name: Workflow B
    runs-on: ubuntu-latest
    steps:
      - name: Using Checkout @v4
        uses: actions/checkout@v4

      - name: Running Workflow B
        id: env
        run: |
          echo "Hello Im workflow B!"
    outputs:
      value: "stage"
