name: test matrix runner
on:
  workflow_push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stages: ['live', 'stage', 'test']
    steps:
      if: ${{matrix.stages == 'live'}}
      - name: live command
        command: echo "live"
      
      if: ${{matrix.stages == 'test'}}
      - name: test command
        command: echo "test"
      
      
  
