name: test matrix runner
on:
  workflow_push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stages: ['live', 'stage', 'test']
    steps:
      - name: live command
        run:|
          if [[ ${{matix.stages -e 'live' ]]; then
            echo "Live"
          
          
