name: test matrix runner
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stages: ['live', 'stage', 'test']
    steps:
      - name: live command
        run: |
          if [[ ${{matrix.stages}} == 'live' ]]; then
            echo "Live"
          fi
          
          if [[ ${{matrix.stages}} == 'stage' ]]; then
            echo "Stage"
          fi
          
          if [[ ${{matrix.stages}} == 'test' ]]; then
            echo "Test"
          fi
          
